version: '3'
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
  py-api:
    restart: always  
    build:
      dockerfile: Dockerfile
      context: ./py-api
    volumes: 
      - ./py-api:/app
    links:
      - redis
    ports:
      - '5000:5000'
    depends_on:
      - redis
    stdin_open: true
  front:
    build:
      dockerfile: Dockerfile
      context: ./front
    volumes:
      - /app/node_modules
      - ./front:/app
    ports:
      - '3000:3000'
    links:
      - py-api
    stdin_open: true
